from __future__ import annotations

from common import (
    build_config,
    ensure_output_dir,
    list_chapter_files,
    list_support_files,
    list_support_markdown_files,
    parse_args_with_version,
    read_text,
    strip_trailing_blank_lines,
    write_json,
    write_text,
)


def build_bundle_text(source_dir) -> tuple[str, dict]:
    chapters = list_chapter_files(source_dir)
    tables = list_support_markdown_files(source_dir, "tables")
    snippets = list_support_files(source_dir, "snippets")
    figures = list_support_files(source_dir, "figures")

    if not chapters:
        raise FileNotFoundError(f"No chapter markdown files found under: {source_dir}")

    lines: list[str] = []
    manifest = {
        "source_dir": str(source_dir),
        "chapters": [],
        "tables": [],
        "snippets": [],
        "figures": [],
    }

    lines.append("<!-- Generated by code/export/build_report_bundle.py -->")
    lines.append("")

    for index, chapter in enumerate(chapters):
        content = read_text(chapter).strip()
        if index > 0:
            lines.extend(["", "---", ""])
        lines.append(content)
        manifest["chapters"].append(chapter.name)

    if tables:
        lines.extend(["", "---", "", "# 附录 A 配套表格", ""])
        lines.append("以下附录由当前报告目录下的 `tables/` Markdown 文件按文件名顺序合并而成。")
        for table in tables:
            raw_lines = strip_trailing_blank_lines(read_text(table).splitlines())
            if raw_lines and raw_lines[0].startswith("# "):
                raw_lines = raw_lines[1:]
                while raw_lines and not raw_lines[0].strip():
                    raw_lines = raw_lines[1:]
            lines.extend(["", "## " + table.stem, ""])
            lines.extend(raw_lines)
            manifest["tables"].append(f"tables/{table.name}")

    if snippets:
        lines.extend(["", "---", "", "# 附录 B 代码片段索引", ""])
        for snippet in snippets:
            lines.extend(["", f"## {snippet.name}", ""])
            lines.append(f"源文件：`snippets/{snippet.name}`")
            lines.append("")
            lines.append("```text")
            lines.extend(strip_trailing_blank_lines(read_text(snippet).splitlines()))
            lines.append("```")
            manifest["snippets"].append(f"snippets/{snippet.name}")

    if figures:
        lines.extend(["", "---", "", "# 附录 C 版本专用图片索引", ""])
        for figure in figures:
            lines.extend(["", f"## {figure.name}", ""])
            lines.append(f"源文件：`figures/{figure.name}`")
            manifest["figures"].append(f"figures/{figure.name}")

    lines.append("")
    return "\n".join(lines), manifest


def main() -> None:
    args = parse_args_with_version()
    config = build_config(args.version, args.source)
    ensure_output_dir(config.output_dir)

    bundle_text, manifest = build_bundle_text(config.source_dir)
    manifest.update(
        {
            "version": config.version,
            "source": config.source,
            "bundle_path": str(config.bundle_path),
        }
    )

    write_text(config.bundle_path, bundle_text)
    write_json(config.manifest_path, manifest)

    print(f"Bundle written: {config.bundle_path}")
    print(f"Manifest written: {config.manifest_path}")


if __name__ == "__main__":
    main()
