from __future__ import annotations

import argparse
import re
from pathlib import Path

from common import REPORT_ROOT
from markdown_to_latex import convert_markdown


CHAPTER_RE = re.compile(r"^(?P<number>\d{2})-.*\.md$")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Migrate active Markdown chapters to the v0.2 LaTeX workspace")
    parser.add_argument("--source", choices=("current",), default="current")
    parser.add_argument("--version", default="v0.2")
    parser.add_argument("--include-00", action="store_true", help="Also convert the navigation entry file")
    return parser.parse_args()


def find_chapters(source_dir: Path, include_00: bool) -> list[Path]:
    chapters: list[Path] = []
    for path in sorted(source_dir.glob("*.md")):
        match = CHAPTER_RE.match(path.name)
        if not match:
            continue
        if match.group("number") == "00" and not include_00:
            continue
        chapters.append(path)
    expected_start = 0 if include_00 else 1
    expected = list(range(expected_start, 28))
    actual = [int(CHAPTER_RE.match(path.name).group("number")) for path in chapters]
    if actual != expected:
        raise ValueError(f"Expected chapter numbers {expected}, found {actual}")
    return chapters


def write_manifest(chapter_dir: Path, chapters: list[Path]) -> Path:
    manifest = chapter_dir / "manifest.tex"
    lines = ["% Generated by code/export/migrate_latex.py; do not edit by hand.", ""]
    for chapter in chapters:
        lines.append(rf"\input{{chapters/{chapter.stem}}}")
    lines.append("")
    manifest.write_text("\n".join(lines), encoding="utf-8")
    return manifest


def main() -> None:
    args = parse_args()
    source_dir = REPORT_ROOT / args.source
    latex_dir = REPORT_ROOT / "latex" / "current"
    chapter_dir = latex_dir / "chapters"
    figures_dir = latex_dir / "figures"
    chapters = find_chapters(source_dir, args.include_00)
    for source in chapters:
        target = chapter_dir / f"{source.stem}.tex"
        convert_markdown(source, target, figures_dir)
        print(f"Migrated: {source.name} -> {target.name}")
    manifest = write_manifest(chapter_dir, chapters)
    print(f"Manifest written: {manifest}")


if __name__ == "__main__":
    main()
